### Read the .csv file

In [26]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd
df = pd.read_csv('Student Performance.csv')

### KNN Model 3

<img src="Model 3.jpg" width=500 height=500 />

### Obtain the feature matrix and label

In [27]:
# convert these data into 2D numpy array
# order: math percentage, reading score percentage, writing score percentage
X = np.array([[df['math percentage'][0], 
              df['reading score percentage'][0], 
              df['writing score percentage'][0]]], 
             dtype = 'float')
for i in range(1,1000):
    X = np.append(X, [[df['math percentage'][i], 
                  df['reading score percentage'][i], 
                  df['writing score percentage'][i]]],axis=0)
print('feature matrix')
print(X)
print('size: ' + str(X.shape))
print()

# Standard = 1, Free/Reduced = 2
if(df['lunch'][0] == 'standard'):
    first_elem = 0
else:
    first_elem = 1
    
y = np.array([first_elem], dtype = 'int')
for i in range(1,1000):
    if(df['lunch'][i] == 'standard'):
        y = np.append(y, 0)
    else:
        y = np.append(y, 1)
print('Labels')
print(y)
print('size: ' + str(y.shape))

feature matrix
[[0.72 0.72 0.74]
 [0.69 0.9  0.88]
 [0.9  0.95 0.93]
 ...
 [0.59 0.71 0.65]
 [0.68 0.78 0.77]
 [0.77 0.86 0.86]]
size: (1000, 3)

Labels
[0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 1 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1
 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 1 1 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1
 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0
 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 0
 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0

In [28]:
# Randomly splitting the original dataset into training set and testing set
# The function"train_test_split" from "sklearn.cross_validation" library performs random splitting.
# "test_size=0.3" means that pick 30% of data samples for testing set, and the rest (70%) for training set.

from sklearn.model_selection import train_test_split
# where X is all the sample data, y is all the labels
# random_state=1 means only random once and rest stay the same
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42) # We can fix the random_state for reproducibility!

In [29]:
# print the size of the traning set:
print(X_train.shape)
print(y_train.shape)

(670, 3)
(670,)


In [30]:
# print the size of the testing set:
print(X_test.shape)
print(y_test.shape)

(330, 3)
(330,)


In [31]:
print(X_test)
print('\n')
print(y_test)

[[0.91 0.86 0.84]
 [0.53 0.66 0.73]
 [0.8  0.73 0.72]
 [0.74 0.77 0.73]
 [0.84 0.83 0.78]
 [0.81 0.75 0.78]
 [0.69 0.7  0.63]
 [0.54 0.61 0.62]
 [0.87 0.73 0.72]
 [0.51 0.54 0.41]
 [0.45 0.47 0.49]
 [0.3  0.26 0.22]
 [0.67 0.8  0.81]
 [0.49 0.65 0.61]
 [0.85 0.81 0.85]
 [0.65 0.78 0.82]
 [0.53 0.52 0.42]
 [0.55 0.46 0.44]
 [0.48 0.58 0.54]
 [0.56 0.65 0.63]
 [0.79 0.72 0.69]
 [0.43 0.51 0.54]
 [0.45 0.73 0.7 ]
 [0.36 0.53 0.43]
 [0.8  0.79 0.79]
 [0.8  0.75 0.77]
 [0.68 0.74 0.74]
 [0.4  0.59 0.51]
 [0.34 0.48 0.41]
 [0.49 0.58 0.6 ]
 [0.62 0.61 0.57]
 [0.71 0.61 0.69]
 [0.62 0.63 0.56]
 [0.76 0.71 0.72]
 [0.84 0.77 0.71]
 [0.45 0.53 0.55]
 [0.77 0.78 0.73]
 [0.69 0.77 0.77]
 [0.73 0.78 0.74]
 [0.   0.17 0.1 ]
 [0.82 0.75 0.77]
 [0.65 0.66 0.62]
 [0.67 0.61 0.68]
 [0.54 0.63 0.67]
 [0.9  0.87 0.75]
 [0.59 0.63 0.75]
 [0.74 0.7  0.69]
 [0.29 0.29 0.3 ]
 [0.89 0.88 0.82]
 [0.75 0.82 0.79]
 [0.71 0.75 0.7 ]
 [0.64 0.76 0.74]
 [0.79 0.79 0.78]
 [0.48 0.56 0.58]
 [0.69 0.73 0.73]
 [0.69 0.7

In [32]:
from sklearn.metrics import accuracy_score
for i in range(1,300):
    k = i
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_predict = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_predict)
    print('k=' + str(i) + ', accuracy=' + str(accuracy))

k=1, accuracy=0.6181818181818182
k=2, accuracy=0.6424242424242425
k=3, accuracy=0.6545454545454545
k=4, accuracy=0.6454545454545455
k=5, accuracy=0.6454545454545455
k=6, accuracy=0.6454545454545455
k=7, accuracy=0.6545454545454545
k=8, accuracy=0.6757575757575758
k=9, accuracy=0.6727272727272727
k=10, accuracy=0.6818181818181818
k=11, accuracy=0.6727272727272727
k=12, accuracy=0.6606060606060606
k=13, accuracy=0.6818181818181818
k=14, accuracy=0.6848484848484848
k=15, accuracy=0.6909090909090909
k=16, accuracy=0.693939393939394
k=17, accuracy=0.6787878787878788
k=18, accuracy=0.6696969696969697
k=19, accuracy=0.6848484848484848
k=20, accuracy=0.6787878787878788
k=21, accuracy=0.6848484848484848
k=22, accuracy=0.6757575757575758
k=23, accuracy=0.6848484848484848
k=24, accuracy=0.6878787878787879
k=25, accuracy=0.696969696969697
k=26, accuracy=0.6878787878787879
k=27, accuracy=0.703030303030303
k=28, accuracy=0.7
k=29, accuracy=0.703030303030303
k=30, accuracy=0.696969696969697
k=31, acc

k=247, accuracy=0.6212121212121212
k=248, accuracy=0.6212121212121212
k=249, accuracy=0.6212121212121212
k=250, accuracy=0.6212121212121212
k=251, accuracy=0.6212121212121212
k=252, accuracy=0.6212121212121212
k=253, accuracy=0.6212121212121212
k=254, accuracy=0.6212121212121212
k=255, accuracy=0.6212121212121212
k=256, accuracy=0.6212121212121212
k=257, accuracy=0.6212121212121212
k=258, accuracy=0.6212121212121212
k=259, accuracy=0.6212121212121212
k=260, accuracy=0.6212121212121212
k=261, accuracy=0.6212121212121212
k=262, accuracy=0.6212121212121212
k=263, accuracy=0.6212121212121212
k=264, accuracy=0.6212121212121212
k=265, accuracy=0.6212121212121212
k=266, accuracy=0.6212121212121212
k=267, accuracy=0.6212121212121212
k=268, accuracy=0.6212121212121212
k=269, accuracy=0.6212121212121212
k=270, accuracy=0.6212121212121212
k=271, accuracy=0.6212121212121212
k=272, accuracy=0.6212121212121212
k=273, accuracy=0.6212121212121212
k=274, accuracy=0.6212121212121212
k=275, accuracy=0.62